#!/bin/bash

export PACKAGE_CORE_NAME="kind"
export PACKAGE_CORE_ORG="kubernetes-sigs"
export PACKAGE_CORE_BIN_NAME="$PACKAGE_CORE_NAME"
export PACKAGE_CORE_VERSION="v0.19.0"

export PACKAGE_CORE_GIT_REPOSITORY="https://github.com/${PACKAGE_CORE_ORG}/${PACKAGE_CORE_NAME}"

export PACKAGE_CORE_RELEASE_DOWNLOAD="https://kind.sigs.k8s.io/dl"
